services:
  postgres:
    image: postgres:16
    container_name: agricore-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: agricore_db
      POSTGRES_USER: agricore_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U agricore_user -d agricore_db"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: