"""add farm memebership

Revision ID: 5298a4df3b9e
Revises: 6b7c8d9e0f12
Create Date: 2026-09-13 08:44:43.300031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5298a4df3b9e'
down_revision: Union[str, Sequence[str], None] = '6b7c8d9e0f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'farm_memberships',
        sa.Column(
            'joined_at',
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text('CURRENT_TIMESTAMP'),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farm_memberships', 'joined_at')
    # ### end Alembic commands ###
