"""harden core database schema

Revision ID: 66e1a664b549
Revises: 10e334752f36
Create Date: 2026-08-27 12:36:07.663164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e1a664b549'
down_revision: Union[str, Sequence[str], None] = '10e334752f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('farm_memberships', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'WORKER', 'VIEWER', name='farm_role'),
               existing_nullable=False)
    op.create_index('ix_farm_memberships_farm_user', 'farm_memberships', ['farm_id', 'user_id'], unique=False)
    op.create_unique_constraint('uq_farm_membership_user_farm', 'farm_memberships', ['user_id', 'farm_id'])
    op.alter_column('farms', 'area',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.create_check_constraint('ck_farms_area_positive', 'farms', 'area IS NULL OR area > 0')
    op.alter_column('fields', 'area',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.create_check_constraint('ck_fields_area_positive', 'fields', 'area IS NULL OR area > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_fields_area_positive', 'fields', type_='check')
    op.alter_column('fields', 'area',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_constraint('ck_farms_area_positive', 'farms', type_='check')
    op.alter_column('farms', 'area',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_constraint('uq_farm_membership_user_farm', 'farm_memberships', type_='unique')
    op.drop_index('ix_farm_memberships_farm_user', table_name='farm_memberships')
    op.alter_column('farm_memberships', 'role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'WORKER', 'VIEWER', name='farm_role'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
