
"""add fields

Revision ID: 8bb01e4da350
Revises: 5298a4df3b9e
Create Date: 2026-09-13 13:40:38.448137

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic.
revision: str = "8bb01e4da350"
down_revision: Union[str, Sequence[str], None] = "5298a4df3b9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""

    # ------------------------------------------------------------------
    # Farm memberships
    # ------------------------------------------------------------------
    #
    # The farm_memberships.role column is already using the PostgreSQL
    # farm_role enum in the current database.
    #
    # PostgreSQL currently contains:
    #
    #   OWNER
    #   ADMIN
    #   MANAGER
    #   WORKER
    #   VIEWER
    #
    # Therefore, we must NOT alter the role column here.
    #
    # The previous autogenerated migration attempted to convert the
    # column from VARCHAR to farm_role again, which caused:
    #
    #   psycopg.errors.DatatypeMismatch:
    #   column "role" cannot be cast automatically to type farm_role
    #
    # No role migration is required in this revision.


    # ------------------------------------------------------------------
    # Fields
    # ------------------------------------------------------------------

    # Add the new area_hectares column.
    #
    # The fields table was verified to contain zero rows, so adding this
    # column as NOT NULL is safe.
    op.add_column(
        "fields",
        sa.Column(
            "area_hectares",
            sa.Float(),
            nullable=False,
        ),
    )

    # Add the field status column.
    #
    # The fields table currently contains zero rows, so adding this
    # required column is also safe.
    op.add_column(
        "fields",
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
        ),
    )

    # The old area column had the following check constraint:
    #
    #   ck_fields_area_positive
    #
    # Since the old area column is being removed, the constraint must
    # also be removed before dropping the column.
    op.drop_constraint(
        "ck_fields_area_positive",
        "fields",
        type_="check",
    )

    # Remove the old area column.
    #
    # area is being replaced by area_hectares.
    op.drop_column(
        "fields",
        "area",
    )


def downgrade() -> None:
    """Downgrade database schema."""

    # ------------------------------------------------------------------
    # Fields
    # ------------------------------------------------------------------

    # Restore the original area column.
    op.add_column(
        "fields",
        sa.Column(
            "area",
            sa.NUMERIC(
                precision=12,
                scale=2,
            ),
            nullable=True,
        ),
    )

    # Restore the original positive-area constraint.
    op.create_check_constraint(
        "ck_fields_area_positive",
        "fields",
        "area IS NULL OR area > 0",
    )

    # Remove the new status column.
    op.drop_column(
        "fields",
        "status",
    )

    # Remove the new area_hectares column.
    op.drop_column(
        "fields",
        "area_hectares",
    )


    # ------------------------------------------------------------------
    # Farm memberships
    # ------------------------------------------------------------------
    #
    # Nothing is required here.
    #
    # The upgrade did not modify farm_memberships.role because the
    # database already had the correct farm_role enum.

